[custom]
;Options for custom groups
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BlockHttpDNS/BlockHttpDNS.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🛑 广告拦截,embedded://base/rules/clash/reject.list
ruleset=📵 手机号一键登录,embedded://base/rules/clash/one_click_login.list
ruleset=🧱 内地,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=🛡️ 隐私防护,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy.list
ruleset=🛡️ 隐私防护,https://raw.githubusercontent.com/SunsetMkt/anti-ip-attribution/main/generated/rule-set-reject.list
ruleset=🧱 内地,https://raw.githubusercontent.com/SunsetMkt/anti-ip-attribution/main/generated/rule-set-direct.list
ruleset=📍 IP归属地,https://raw.githubusercontent.com/SunsetMkt/anti-ip-attribution/main/generated/rule-set-proxy.list
;ruleset=🔒 iCloud PR,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/iCloudPrivateRelay/iCloudPrivateRelay.list
ruleset=💰 PayPal,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.list
ruleset=🤖 AI,embedded://base/rules/clash/ai_platform.list
;ruleset=🪙 交易所,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Binance/Binance.list
;ruleset=🪙 交易所,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OKX/OKX.list
;ruleset=🙈 机场屏蔽,https://raw.githubusercontent.com/Monopink/my-sub/main/base/rules/clash/proxy_provider_block.list
ruleset=🌊 下载流量,embedded://base/rules/clash/download.list
ruleset=🌊 下载流量,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownload/GameDownload.list
ruleset=🌊 下载流量,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.list
;ruleset=🎮 游戏,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gog/Gog.list
;ruleset=🎮 游戏,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Battle/Battle.list
;ruleset=🎮 游戏,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list
;ruleset=🎮 游戏,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hearthstone/Hearthstone.list
;ruleset=📢 Google FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
;ruleset=💬 Zalo,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Zalo/Zalo.list
;ruleset=💬 Line,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Line/Line.list
ruleset=🌩️ OneDrive,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
ruleset=🪟 Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🍏 Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
ruleset=✈️ Telegram,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
;ruleset=🛍️ TikTok Shop,https://raw.githubusercontent.com/Monopink/my-sub/main/base/rules/clash/tiktok_shop.list
ruleset=📺 YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=🥝 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
;ruleset=🏰 DisneyPlus,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
;ruleset=🍺 Bilibili港澳台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📡 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list
;ruleset=🇹🇼 台湾网站,[]DOMAIN-SUFFIX,tw
ruleset=🌐 国际,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nvidia/Nvidia.list
ruleset=🌐 国际,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🌐 国际,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=📍 IP归属地,embedded://base/rules/clash/ip_location.list
ruleset=🧱 内地,embedded://base/rules/clash/direct.list
ruleset=🧱 内地,embedded://base/rules/clash/LanZouYun.list
ruleset=🧱 内地,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=🧱 内地,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🧱 内地,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🧱 内地,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🧱 内地,[]GEOIP,CN,no-resolve
ruleset=🌐 国际,[]FINAL

;Options for custom rulesets
enable_rule_generator=true
overwrite_original_rules=true
custom_proxy_group=🌐 国际`select`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定`[]DIRECT
custom_proxy_group=🧱 内地`select`[]DIRECT`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
custom_proxy_group=🔘 全部自定`select`.*`[]DIRECT`[]REJECT
;custom_proxy_group=🟡 手动选择2`select`.*`[]DIRECT`[]REJECT
;custom_proxy_group=🟢 手动选择3`select`.*`[]DIRECT`[]REJECT
;custom_proxy_group=🔵 手动选择4`select`.*`[]DIRECT`[]REJECT
;custom_proxy_group=🟣 手动选择5`select`.*`[]DIRECT`[]REJECT
custom_proxy_group=⚪ 其他自定`select`.+

custom_proxy_group=📍 IP归属地`select`[]🌐 国际`[]🧱 内地`[]DIRECT`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
custom_proxy_group=🌊 下载流量`select`[]🧱 内地`[]DIRECT`[]🌐 国际`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
custom_proxy_group=📡 流媒体`select`[]🌐 国际`[]🧱 内地`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定

;custom_proxy_group=🛍️ TikTok Shop`select`[]🎵 TikTok`[]🌐 国际`(泰国|菲律宾|印度尼|马来|越南|新加坡)`[]🧱 内地`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
custom_proxy_group=🎵 TikTok`select`[]📡 流媒体`[]🌐 国际`(泰国|菲律宾|印度尼|马来|越南|新加坡)`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
custom_proxy_group=🥝 Spotify`select`[]📡 流媒体`[]🌐 国际`[]🧱 内地`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
custom_proxy_group=🤖 AI`select`[]🌐 国际`[]🧱 内地`[]🌏 东亚均流`[]🌏 东亚低延`[]🔀 主要均流`[]➡️ 主要低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
custom_proxy_group=💰 PayPal`select`[]DIRECT`.+`[]🌐 国际`[]🧱 内地`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
;custom_proxy_group=🪙 交易所`select`[]🌐 国际`[]🧱 内地`[]🌏 东亚均流`[]🌏 东亚低延`.+`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
;custom_proxy_group=💬 Line`select`[]🌐 国际`[]🧱 内地`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
;custom_proxy_group=💬 Zalo`select`(越南)`[]🌐 国际`[]🧱 内地`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
;custom_proxy_group=🎮 游戏`select`[]🌐 国际`[]🧱 内地`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
custom_proxy_group=🌩️ OneDrive`select`[]🌐 国际`[]🧱 内地`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
custom_proxy_group=🪟 Microsoft`select`[]🧱 内地`[]🌐 国际`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
;custom_proxy_group=🔒 iCloud PR`select`[]🌐 国际`[]🧱 内地`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
custom_proxy_group=🍏 Apple`select`[]🧱 内地`[]🌐 国际`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
custom_proxy_group=✈️ Telegram`select`[]🌐 国际`[]🧱 内地`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定

;custom_proxy_group=🍺 Bilibili港澳台`select`[]🧱 内地`[]🌐 国际`[]🔀 主要均流`[]➡️ 主要低延`(香港|🇭🇰|HK|澳门|🇲🇴|MO|台湾|🇹🇼|TW)`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
custom_proxy_group=📺 YouTube`select`[]📡 流媒体`[]🌐 国际`[]🧱 内地`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
custom_proxy_group=🎥 Netflix`select`[]📡 流媒体`[]🌐 国际`[]🧱 内地`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
;custom_proxy_group=🏰 DisneyPlus`select`[]📡 流媒体`[]🌐 国际`[]🧱 内地`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
;custom_proxy_group=🇹🇼 台湾网站`select`[]🌐 国际`(🇹🇼|台湾|TW|Taiwan)`[]🧱 内地`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定
;custom_proxy_group=🙈 机场屏蔽`select`[]🌐 国际`[]🧱 内地`[]🔀 主要均流`[]➡️ 主要低延`[]🌏 东亚均流`[]🌏 东亚低延`[]🇭🇰 港澳均流`[]🇭🇰 港澳低延`[]🇯🇵 日本均流`[]🇯🇵 日本低延`[]🇹🇼 台湾均流`[]🇹🇼 台湾低延`[]🇸🇬 新加坡均流`[]🇸🇬 新加坡低延`[]🇺🇸 美国均流`[]🇺🇸 美国低延`[]🔘 全部自定`[]⚪ 其他自定

custom_proxy_group=📵 手机号一键登录`select`[]DIRECT`[]REJECT`[]🌐 国际`[]🧱 内地`[]🔘 全部自定
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]🌐 国际`[]🧱 内地`[]🔘 全部自定`[]DIRECT
custom_proxy_group=🛡️ 隐私防护`select`[]REJECT`[]🌐 国际`[]🧱 内地`[]🔘 全部自定`[]DIRECT

custom_proxy_group=🔀 主要均流`load-balance`(🇭🇰|HK|香港|🇲🇴|MO|澳门|🇹🇼|TW|台湾|🇸🇬|SG|新加坡|🇯🇵|JP|日本|🇮🇩|ID|印度尼|印尼|🇵🇭|PH|菲律宾|🇲🇾|MY|马来)`https://i.ytimg.com/generate_204`300,,50
custom_proxy_group=➡️ 主要低延`url-test`(🇭🇰|HK|香港|🇲🇴|MO|澳门|🇹🇼|TW|台湾|🇸🇬|SG|新加坡|🇯🇵|JP|日本|🇮🇩|ID|印度尼|印尼|🇵🇭|PH|菲律宾|🇰🇷|KR|韩国|🇲🇾|MY|马来|🇹🇭|TH|泰国)`https://i.ytimg.com/generate_204`180,,50

custom_proxy_group=🇭🇰 港澳均流`load-balance`(🇭🇰|🇲🇴|HK|MO|香港|澳门)`https://i.ytimg.com/generate_204`300,,50
custom_proxy_group=🇭🇰 港澳低延`url-test`(🇭🇰|🇲🇴|HK|MO|香港|澳门)`https://i.ytimg.com/generate_204`300,,50
custom_proxy_group=🌏 东亚均流`load-balance`(🇹🇼|TW|台湾|🇸🇬|SG|新加坡|🇯🇵|JP|日本|🇮🇩|ID|印度尼|印尼|🇵🇭|PH|菲律宾|🇲🇾|MY|马来)`https://i.ytimg.com/generate_204`300,,50
custom_proxy_group=🌏 东亚低延`url-test`(🇹🇼|TW|台湾|🇸🇬|SG|新加坡|🇯🇵|JP|日本|🇮🇩|ID|印度尼|印尼|🇵🇭|PH|菲律宾|🇲🇾|MY|马来)`https://i.ytimg.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本均流`load-balance`(🇯🇵|日本|JP|Japan)`https://i.ytimg.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本低延`url-test`(🇯🇵|日本|JP|Japan)`https://i.ytimg.com/generate_204`300,,50
custom_proxy_group=🇹🇼 台湾均流`load-balance`(🇹🇼|台湾|TW|Taiwan)`https://i.ytimg.com/generate_204`300,,50
custom_proxy_group=🇹🇼 台湾低延`url-test`(🇹🇼|台湾|TW|Taiwan)`https://i.ytimg.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡均流`load-balance`(🇸🇬|新加坡|狮城|SG|Singapore)`https://i.ytimg.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡低延`url-test`(🇸🇬|新加坡|狮城|SG|Singapore)`https://i.ytimg.com/generate_204`300,,50
custom_proxy_group=🇺🇸 美国均流`load-balance`(🇺🇸|美国|US|United States)`https://i.ytimg.com/generate_204`300,,150
custom_proxy_group=🇺🇸 美国低延`url-test`(🇺🇸|美国|US|United States)`https://i.ytimg.com/generate_204`300,,150

;Options for custom base configuration file
clash_rule_base=embedded://base/base/clash.yaml
;surge_rule_base=base/surge.conf
;surfboard_rule_base=base/surfboard.conf
;mellow_rule_base=base/mellow.conf
;quan_rule_base=base/quan.conf
;quanx_rule_base=embedded://base/base/quanx.conf
;loon_rule_base=base/loon.conf
;sssub_rule_base=base/shadowsocks_base.json
;singbox_rule_base=base/singbox.json

;Options for renaming nodes
;rename=Test-(.*?)-(.*?)-(.*?)\((.*?)\)@\1\4x测试线路_自\2到\3
;rename=\(?((x|X)?(\d+)(\.?\d+)?)((\s?倍率?)|(x|X))\)?@$1x

;Options for adding emojis
add_emoji=false
remove_old_emoji=false
;emoji=(流量|时间|应急),🏳️‍🌈
;emoji=阿根廷,🇦🇷
emoji=台湾,🇹🇼

;Options for filtering nodes
;include_remarks=
;exclude_remarks=

;[template]
;;variables in the local scope
;clash.dns.port=5353
